Config:
  DefaultParrotColor: BLUE
  DefaultSide: Right
  isSilent: true
Messages:
  GuiName: §5Parrot Menu!
  ParrotSelected: §c§5[§bParrots§5] §dParrot Selected!
  NoPermissions: §5[§bParrots§5] §cYou do not have permissions to do this!
  ShoulderSwitched: §5[§bParrots§5] §dParrot shoulder switched!
  ParrotRemoved: §5[§bParrots§5] §dParrot Removed!
  YouRemovedParrot: §5[§bParrots§5] §dYou removed players %PLAYER% parrot!
  Reloaded: §5[§bParrots§5] §dPlugin Reloaded!
  ParrotSet: §5[§bParrots§5] §dParrot set!
  SetMessage: §5[§bParrots§5] §dTo set Parrot for player you must use /parrots set (Player) (side [Right,Left,Both]) (color [Gray,Blue,Cyan,Green,Red])
  InvalidArguments: §5[§bParrots§5] §dInvalid Arguments!
  PlayerOnlyCommand: §5[§bParrots§5] §dOnly players can execute this command!
  PlayerNotFound: §5[§bParrots§5] §cPlayer Not Found!
  PlayerDoesNotHaveParrot: §5[§bParrots§5] §cPlayer Does Not Have Parrot!
  YouDontHaveParrot: §5[§bParrots§5] §cYou don't have a parrot!
Items:
  GrayParrot:
    Name: §7§lGray!
    Lore: §7Red Parrot!
  BlueParrot:
    Name: §2§lBlue!
    Lore: §2Blue Parrot!
  CyanParrot:
    Name: §b§lCyan!
    Lore: §bCyan Parrot!
  GreenParrot:
    Name: §a§lGreen!
    Lore: §aGreen Parrot!
  RedParrot:
    Name: §c§lRed!
    Lore: §cRed Parrot!
  RemoveParrot:
    Name: §c§lRemove!
    Lore: §cRemove Parrot!
  SwitchShoulder:
    Name: §c§lShoulder
    LoreRight: '§7Side: §9Right'
    LoreLeft: '§7Side: §9Left'
    LoreBoth: '§7Side: §9Both'